version: '3.8'
services:
  prometheus:
    hostname: random-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/config.yml

  grafana:
    hostname: random-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning

  api:
    hostname: api
    build:
      context: .
      dockerfile: Dockerfile
      #command: python3.9 app.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
