{
 "title": "App Comentarios",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{instance=\"api:8000\"}"
    }
   ]
  },
  {
   "title": "Status CPU ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"api:8000\",job=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Request Total - Status 200",
   "type": "timeseries",
   "description": "Status 200",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_total{instance=\"api:8000\",method=\"GET\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Request Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_created{instance=\"api:8000\",method=\"GET\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_collections_total{instance=\"api:8000\",job=\"monitoring\"}"
    }
   ]
  },
  {
   "title": "Request Duration Seconds Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_duration_seconds_count{instance=\"api:8000\",method=~\"GET|POST\"}"
    }
   ]
  }
 ]
}