global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - “first.rules”
# - “second.rules”

scrape_configs:
- job_name: monitoring
  static_configs:
  - targets:
          - api:8000
            #- 177.38.215.196:80

            #- job_name: 'app'
            #scrape_interval: 1s
            # metrics_path: '/metrics'
            #  static_configs:
            #  - targets: ['localhost:8000']

    #- job_name: 'prober'
    # scrape_interval: 5s
    # metrics_path: '/metrics'
    #static_configs:
    #- targets: ['prober:8000']
